name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest

      - name: Install
        run: yarn install

      - name: Optimize assets
        run: npx expo-optimize

      - name: Build
        run: yarn build:web

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "web-build/"
          REMOTE_HOST: ${{ secrets.DEPLOY_IP }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          TARGET: ${{ secrets.DEPLOY_TARGET }}